name: SeleniumExtras
description: $description
version: '${version}'

main: com.moonlightpowered.seleniumextras.SeleniumExtras
bootstrapper: com.moonlightpowered.seleniumextras.SeleniumExtrasBootstrap
loader: com.moonlightpowered.seleniumextras.SeleniumExtrasLoader
api-version: '26.3'
load: STARTUP

authors: [ Biquaternions ]
